spring:
  datasource:
    url: "jdbc:mysql://103.141.140.12:3306/db_haivanvn?useLegacyDatetimeCode=false&serverTimezone=GMT%2B7&useUnicode=true&characterEncoding=utf8"
    username: "tc"
    password: "tc@12345"
    hikari:
      connection-timeout: 30000 # 30 seconds
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 120000 # 2 minutes
      max-lifetime: 1800000 # 30 minutes
  redis:
    host: "3.1.31.233"
    port: 6379
    password: "HavzReeedisjYR8r25tyZ2011"

# Havaz
havaz:
  security:
    jwt-secret-key: "4d338ae78c421c0ad50dc65632f5519880120e3469b5e5a67f79484670ca74ce741155902ffd201cc660e7608ec49957ff3be0ae90eed2f590a1ab294bb76824"
  mqtt:
    url: "wss://emqx.havazdev.net:8087"
    username: "mqtt"
    password: "HazClients@123"
    queue:
      tracking-driver: "HSHV_queue_driver"
  redis:
    key: "HSHV_KEY"
    pubsub:
      channel: "notify_to_manager_hason_haivan_dev"
  rabbitmq:
    san:
      host: "202.134.19.11"
      port: 5672
      username: "shavaz"
      password: "HazavSA12B4nvE@2020"
      virtual-host: "/"
      on-send-message: true
      exchange: "transport.tracking"
      routing-key: "transport.tracking.updatepickuptime"
      driver.arrived:
        queue: "transport.tracking.driver"
        routing-key: "transport.tracking.driver.has.arrived"
      driver.confirmed:
        queue: "transport.rabbitmq.driver.confirmed"
        routing-key: "transport.rabbitmq.driver.confirmed.routing"
    erp:
      host: "103.141.140.12"
      port: 5672
      username: "erp"
      password: "havaz@erp"
      virtual-host: "hasonhaivan"
      queue:
        transfer-ticket: "4-queue-transshipments-ticket"
        transfer-ticket-sync: "4-sync-queue-transshipments-ticket"
    transport.transferticket:
      exchange: "4-transshipments-ticket"
      routing-key: "transport.transferticket.update"
      queue: "4-queue-update-ticket"
  stomp:
    topic: "/topic/noti"
  firebase:
    cmd.havaznow.topic: "/topics/cmdhavaz-now-" # firebase-appTopic
  sms:
    hotlines: ""
  time-delay: 5
  number-driver-limit: 2
  number-minute-limit: 60000
  url-erp: "https://dev.hasonhaivan.com/api/transshipment/"
  url-san: "http://dev.api.havaz.vn"
  url-monitor-transfer-ticket: "https://dev.admin.hasonhaivan.com/cron/"
  url-erp-token: "19996a4883ea9acce9c91ec52d85da83"
